# 测试残差正交的效果

结论：
1. 对alpha进行残差正交并不会影响alpha因子的回归系数
2. 对alpha进行残差会影响risk因子的回归系数

In [2]:
import pandas as pd
import os
import numpy as np
#import tushare as ts

os.chdir("E:\\python\\project\\Cubicial_Quant")

# 先组合因子，再产生y

In [6]:
x = (np.random.random(10000)* 10).reshape(2000,5)
x

array([[0.95992644, 0.29740538, 8.07207903, 4.26517082, 9.8688344 ],
       [7.66399246, 4.56690374, 4.92253012, 7.32737101, 3.85210607],
       [2.63619461, 9.0023287 , 6.87709723, 0.42257403, 2.15728482],
       ...,
       [1.8556493 , 5.76815066, 8.13504373, 2.13188112, 7.63904623],
       [6.61517947, 8.7481047 , 3.75389053, 0.25687306, 9.88180845],
       [3.75154625, 0.14699595, 9.66317253, 1.07223207, 9.20615716]])

In [7]:
x_mat = np.ones(20000).reshape(2000,10)

In [8]:
x_mat[:,:5] = x

In [24]:
np.random.seed(42)
x_mat[:,6] = x_mat[:,[4,1]].dot(np.array([0.5,0.6])) + np.random.rand(2000) + 1
x_mat[:,7] = x_mat[:,[2,3]].dot(np.array([0.5,0.6])) + np.random.rand(2000) + 1
x_mat[:,8] = x_mat[:,[2,4]].dot(np.array([0.5,0.6])) + np.random.rand(2000) + 1
x_mat[:,9] = x_mat[:,[1,3]].dot(np.array([0.5,0.6])) + np.random.rand(2000) + 1
x_mat[:,5] = x_mat[:,[4,3]].dot(np.array([0.5,0.6])) + np.random.rand(2000) + 1

In [25]:
import statsmodels.api as sm

In [26]:
x_mat_cons = sm.add_constant(x_mat)

In [27]:
y = x_mat_cons.dot(np.array([0.6,0.7,0.8,0.9,1.1,1.2,1.3,1.4,1.5,1.6,1.7])) + np.random.rand(2000) 

In [28]:
coef_cons_uno = sm.OLS(y,x_mat_cons).fit().params
coef_cons_uno

array([1.09738762, 0.69814565, 0.7747947 , 0.9067373 , 1.08306914,
       1.24543534, 1.25697594, 1.40581637, 1.52935201, 1.55766761,
       1.74548639])

In [29]:
for i in range(5,10):
    coef = sm.OLS(x_mat[:,i],x_mat_cons[:,:6]).fit().params
    residue = x_mat[:,i] - x_mat_cons[:,:6].dot(coef)
    x_mat[:,i] = residue

In [30]:
x_mat_cons = sm.add_constant(x_mat)
coef_cons_or = sm.OLS(y,x_mat_cons).fit().params
coef_cons_or

array([12.35379286,  0.69845235,  2.49772236,  2.44259218,  3.79673807,
        3.5058327 ,  1.25697594,  1.40581637,  1.52935201,  1.55766761,
        1.74548639])

正交因子的系数都没有变化，作为基准的因子的系数增大

# 改变y的组合方式，先产生y，再组合因子

In [46]:
for i in range(5,10):
    x_mat[:,i] = np.random.rand(2000)
x_mat_cons = sm.add_constant(x_mat)

# 产生y
y = x_mat_cons.dot(np.array([0.6,0.7,0.8,0.9,1.1,1.2,1.3,1.4,1.5,1.6,1.7]))   

#组合因子
x_mat[:,6] = x_mat[:,6]+ x_mat[:,:5].dot(np.array([0.1]*5))+ 0.1
x_mat[:,7] = x_mat[:,7]+ x_mat[:,:5].dot(np.array([0.15]*5))+ 0.1
x_mat[:,8] = x_mat[:,8]+ x_mat[:,:5].dot(np.array([0.2]*5))+ 0.1
x_mat[:,9] = x_mat[:,9]+ x_mat[:,:5].dot(np.array([0.25]*5))+ 0.1
x_mat[:,5] = x_mat[:,5]+ x_mat[:,:5].dot(np.array([0.3]*5))+ 0.1
x_mat_cons = sm.add_constant(x_mat)

In [47]:
coef_cons_uno = sm.OLS(y,x_mat_cons).fit().params
coef_cons_uno

array([-0.15, -0.8 , -0.7 , -0.6 , -0.4 , -0.3 ,  1.3 ,  1.4 ,  1.5 ,
        1.6 ,  1.7 ])

In [48]:
# 正交化
for i in range(5,10):
    coef = sm.OLS(x_mat[:,i],x_mat_cons[:,:6]).fit().params
    residue = x_mat[:,i] - x_mat_cons[:,:6].dot(coef)
    x_mat[:,i] = residue

In [49]:
x_mat_cons = sm.add_constant(x_mat)
coef_cons_or = sm.OLS(y,x_mat_cons).fit().params
coef_cons_or

array([4.32296524, 0.6878245 , 0.80856167, 0.90481132, 1.09904009,
       1.20292842, 1.3       , 1.4       , 1.5       , 1.6       ,
       1.7       ])

In [50]:
sum(x_mat)

array([ 9.84000981e+03,  1.00851300e+04,  1.00262423e+04,  9.96850975e+03,
        1.01036118e+04, -2.23909780e-12, -1.04183329e-12, -2.54063437e-12,
       -1.78346227e-12, -5.51469981e-12])

In [51]:
np.random.rand(2000)

array([0.00756341, 0.66353845, 0.91346002, ..., 0.70891607, 0.75669601,
       0.61296342])

# 实例测试

In [67]:
# 阅读市值作为因子
factor = pd.read_csv("./alpha/alpha10.csv",index_col = 0)

In [68]:
re = pd.read_csv("./data/Return.csv",index_col = 0)

In [69]:
re = re.reindex(index = factor.index,columns = factor.columns)

In [78]:
x = factor.iloc[:,-10:]
y = re.iloc[:,-1]

In [79]:
factor

20000110   20000111   20000112   20000113   20000114  \
S_INFO_WINDCODE                                                          
000001.SZ        14.955079  14.896810  14.855988  14.850491  14.836054   
000002.SZ        13.344058  13.290185  13.254500  13.252586  13.212522   
000003.SZ        12.264642  12.191260  12.187870  12.222903  12.167286   
000004.SZ        11.373662  11.375590  11.324196  11.307835  11.337294   
000005.SZ        12.802517  12.766202  12.722355  12.719259  12.736170   
000006.SZ        12.522292  12.457383  12.423278  12.416109  12.389024   
000007.SZ        11.834962  11.769382  11.729717  11.725082  11.683582   
000008.SZ        12.864779  12.879911  12.906219  12.949517  12.992697   
000009.SZ        12.821530  12.787271  12.771055  12.771055  12.779196   
000010.SZ        11.714384  11.647278  11.610624  11.611957  11.584965   
000011.SZ        12.918961  12.853093  12.816988  12.803665  12.779531   
000012.SZ        12.909552  12.849137  12.809204  12.807351  12.798031   
000013.SZ        12.606530  12.544697  12.490270  12.476476  12.448306   
000014.SZ        11.007622  10.962022  10.919124  10.935227  10.923982   
000015.SZ        11.436030  11.385541  11.339871  11.367523  11.341738   
000016.SZ        13.846608  13.777994  13.738000  13.724305  13.704323   
000017.SZ        12.533907  12.482522  12.441700  12.478879  12.462320   
000018.SZ        12.463110  12.402444  12.392668  12.362751  12.308523   
000019.SZ        12.289434  12.258278  12.223667  12.218741  12.207984   
000020.SZ        12.305310  12.300169  12.248604  12.241797  12.219697   
000021.SZ        14.577419  14.521487  14.476723  14.473692  14.447546   
000022.SZ        12.704570  12.646116  12.609839  12.593140  12.572197   
000023.SZ        11.865167  11.806917  11.770052  11.762512  11.761431   
000024.SZ        13.087379  13.043748  12.998126  12.985479  12.953144   
000025.SZ        12.299657  12.193963  12.158792  12.158792  12.157636   
000026.SZ        12.259249  12.209571  12.174170  12.159911  12.163820   
000027.SZ        13.571292  13.521460  13.489318  13.503043  13.494331   
000028.SZ        12.215353  12.155719  12.112720  12.129278  12.109199   
000029.SZ        13.289249  13.227446  13.197869  13.201615  13.201615   
000030.SZ        12.111724  12.072947  12.098964  12.141390  12.113307   
...                    ...        ...        ...        ...        ...   
603937.SH              NaN        NaN        NaN        NaN        NaN   
603938.SH              NaN        NaN        NaN        NaN        NaN   
603939.SH              NaN        NaN        NaN        NaN        NaN   
603955.SH              NaN        NaN        NaN        NaN        NaN   
603958.SH              NaN        NaN        NaN        NaN        NaN   
603959.SH              NaN        NaN        NaN        NaN        NaN   
603960.SH              NaN        NaN        NaN        NaN        NaN   
603963.SH              NaN        NaN        NaN        NaN        NaN   
603966.SH              NaN        NaN        NaN        NaN        NaN   
603968.SH              NaN        NaN        NaN        NaN        NaN   
603969.SH              NaN        NaN        NaN        NaN        NaN   
603970.SH              NaN        NaN        NaN        NaN        NaN   
603976.SH              NaN        NaN        NaN        NaN        NaN   
603977.SH              NaN        NaN        NaN        NaN        NaN   
603978.SH              NaN        NaN        NaN        NaN        NaN   
603979.SH              NaN        NaN        NaN        NaN        NaN   
603980.SH              NaN        NaN        NaN        NaN        NaN   
603985.SH              NaN        NaN        NaN        NaN        NaN   
603986.SH              NaN        NaN        NaN        NaN        NaN   
603987.SH              NaN        NaN        NaN        NaN        NaN   
603988.SH              NaN        NaN        NaN        NaN        NaN   
603989.SH             

In [80]:
y

S_INFO_WINDCODE
000001.SZ   -0.003174
000002.SZ   -0.015259
000003.SZ         NaN
000004.SZ    0.011041
000005.SZ    0.003431
000006.SZ   -0.011112
000007.SZ    0.020338
000008.SZ    0.028568
000009.SZ    0.013249
000010.SZ   -0.002942
000011.SZ    0.000000
000012.SZ    0.004852
000013.SZ         NaN
000014.SZ   -0.012188
000015.SZ         NaN
000016.SZ   -0.006098
000017.SZ   -0.012298
000018.SZ   -0.029523
000019.SZ    0.000000
000020.SZ    0.011506
000021.SZ    0.001695
000022.SZ         NaN
000023.SZ   -0.016478
000024.SZ         NaN
000025.SZ    0.004752
000026.SZ   -0.001276
000027.SZ    0.001953
000028.SZ    0.010184
000029.SZ         NaN
000030.SZ    0.023868
               ...   
603937.SH    0.024201
603938.SH    0.035403
603939.SH    0.048619
603955.SH   -0.005522
603958.SH    0.014563
603959.SH    0.013477
603960.SH    0.006685
603963.SH    0.026576
603966.SH   -0.012146
603968.SH    0.005874
603969.SH    0.016642
603970.SH    0.006094
603976.SH    0.035860
603977.SH    0.0

In [81]:
y = y.dropna()

In [82]:
x = x.reindex(index = y.index)

In [84]:
x = x.dropna(how = "any",axis = 1)
y = y.reindex(index=  x.index)

In [85]:
x_mat = x.values
y_values = y.values

In [86]:
x.shape,y.shape

((3356, 10), (3356,))

In [87]:
x_mat_cons  = sm.add_constant(x_mat)
coef_unor = sm.OLS(y_values,x_mat_cons).fit().params
coef_unor

array([ 4.02011244e-04,  3.21982331e-03, -5.01696440e-03,  1.05905203e-03,
       -1.65785495e-03,  1.66259648e-03, -1.59842493e-03,  9.32078771e-05,
        2.37634540e-03, -1.00448318e+00,  1.00433124e+00])

In [88]:
# 对后5列残差正交化
for i in range(5,10):
    coef = sm.OLS(x_mat[:,i],x_mat_cons[:,:6]).fit().params
    residue = x_mat[:,i] - x_mat_cons[:,:6].dot(coef)
    x_mat[:,i] = residue
x_mat_cons = sm.add_constant(x_mat)

In [89]:
coef_or = sm.OLS(y_values,x_mat_cons).fit().params
coef_or

array([ 2.75052605e-02,  8.26397420e-02, -2.11762731e-01,  1.35508321e-01,
        6.76019194e-02, -7.54856942e-02, -1.59842493e-03,  9.32078771e-05,
        2.37634540e-03, -1.00448318e+00,  1.00433124e+00])

正交因子的回归系数依然不变

In [90]:
coef_or == coef_unor

array([False, False, False, False, False, False, False, False, False,
       False, False])